import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar/Sidebar'
import { cookies } from 'next/headers'
import { AccessToken, SpotifyApi, UserProfile } from '@spotify/web-api-ts-sdk'
import { LogUser } from '@/components/LogUser/LogUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const accessToken = cookies().get(process.env.ACCESS_TOKEN_COOKIE_NAME);
  var spotifyUserProfile : UserProfile = null as any as UserProfile;
  if (accessToken !== undefined && accessToken !== null) {
    spotifyUserProfile = await SpotifyApi.withAccessToken(process.env.SPOTIFY_CLIENT_ID, { access_token: accessToken.value } as any).currentUser.profile();
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='grid grid-cols-[5rem_1fr]'>
          <div className='col-auto'><Sidebar /></div>
          <div className='col-auto'>{children}</div>
        </div>
        {spotifyUserProfile !== null && <LogUser user={spotifyUserProfile} />}
        </body>
    </html>
  )
}

export default RootLayout;